# Best model Selection

In [2]:
# import libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
df=sns.load_dataset("titanic")
x=df[['pclass','sex','age','sibsp','parch','fare']]
y=df['survived']
x=pd.get_dummies(x,columns=['sex'])
x.age.fillna(value=x['age'].mean(),inplace=True)
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,f1_score,precision_score,recall_score
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
models=[LogisticRegression(),SVC(),DecisionTreeClassifier(),RandomForestClassifier(),KNeighborsClassifier()]
model_names=["Logistic Regression","SVM","Decision Tree","Random Forest","KNN"]
models_scores = []
for model, model_name in zip(models, model_names):
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)
    accuracy=accuracy_score(y_test,y_pred)
    models_scores.append([model_name,accuracy])
    sorted_models=sorted(models_scores, key=lambda x: x[1], reverse=True)
    for model in sorted_models:
        print("Accuracy score:",f'{model[0]}: {model[1]:.2f}')

C:\Users\Hair\AppData\Local\Temp\ipykernel_11832\1240524745.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  x.age.fillna(value=x['age'].mean(),inplace=True)

Accuracy score: Logistic Regression: 0.81
Accuracy score: Logistic Regression: 0.81
Accuracy score: SVM: 0.66
Accuracy score: Logistic Regression: 0.81
Accuracy score: Decision Tree: 0.76
Accuracy score: SVM: 0.66
Accuracy score: Logistic Regression: 0.81
Accuracy score: Random Forest: 0.80
Accuracy score: Decision Tree: 0.76
Accuracy score: SVM: 0.66
Accuracy score: Logistic Regression: 0.81
Accuracy score: Random Forest: 0.80
Accuracy score: Decision Tree: 0.76
Accuracy score: KNN: 0.69
Accuracy score: SVM: 0.66

In [3]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [4]:
x

     pclass        age  sibsp  parch     fare  sex_female  sex_male
0         3  22.000000      1      0   7.2500       False      True
1         1  38.000000      1      0  71.2833        True     False
2         3  26.000000      0      0   7.9250        True     False
3         1  35.000000      1      0  53.1000        True     False
4         3  35.000000      0      0   8.0500       False      True
..      ...        ...    ...    ...      ...         ...       ...
886       2  27.000000      0      0  13.0000       False      True
887       1  19.000000      0      0  30.0000        True     False
888       3  29.699118      1      2  23.4500        True     False
889       1  26.000000      0      0  30.0000       False      True
890       3  32.000000      0      0   7.7500       False      True

[891 rows x 7 columns]

In [5]:
models=[LogisticRegression(), SVC(),DecisionTreeClassifier(),RandomForestClassifier(),KNeighborsClassifier()]
model_names=['Logistic Regression','SVM','Decision Tree','Random Forest','KNN']
models_scores=[]
for model,model_name in zip(models, model_names):
    model.fit(x_train,y_train)
    y_pred=model.predict(x_test)
    precision=precision_score(y_test,y_pred)
    models_scores.append([model_name,precision])
sorted_models=sorted(models_scores, key=lambda x: x[1], reverse=True)
for model in sorted_models:
    print("precision_score:",f'{model[0]}:{model[1]:.2f}')

precision_score: Logistic Regression:0.80
precision_score: Random Forest:0.76
precision_score: SVM:0.76
precision_score: Decision Tree:0.72
precision_score: KNN:0.66